# Generated by Django 4.0.3 on 2022-04-13 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_package',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='dob'),
        ),
    ]
