# Generated by Django 4.0.3 on 2022-04-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_package_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_package',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking_package',
            name='zipcode',
        ),
    ]
