# Generated by Django 4.0.3 on 2022-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_booking_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_package',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='booking_package',
            name='zipcode',
            field=models.CharField(default='38001', max_length=30, verbose_name='zipcode'),
        ),
    ]
