# Generated by Django 4.0.3 on 2022-04-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_booking_hotel_hotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_hotel',
            name='zipcode',
        ),
    ]
