# Generated by Django 4.0.3 on 2022-04-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_booking_hotel_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_hotel',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='booking_hotel',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='booking_hotel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='booking_hotel',
            name='fullname',
            field=models.CharField(max_length=30, null=True, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='booking_hotel',
            name='rooms',
            field=models.IntegerField(null=True, verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='booking_hotel',
            name='state',
            field=models.CharField(max_length=30, null=True, verbose_name='state'),
        ),
    ]
