# Generated by Django 4.0.3 on 2022-04-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_booking_hotel_address_alter_booking_hotel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_package',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='booking_package',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='booking_package',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking_package',
            name='user_id',
        ),
    ]
