# Generated by Django 4.0.3 on 2022-04-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_booking_package_hotel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_package',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.package_master'),
        ),
    ]
