# Generated by Django 4.0.3 on 2022-04-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking_package_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_package',
            name='package_id',
        ),
        migrations.AddField(
            model_name='booking_package',
            name='pack_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='pack_name'),
        ),
    ]
