# Generated by Django 4.0.3 on 2022-04-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_booking_package_package_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_package',
            name='pack_name',
            field=models.CharField(max_length=50, verbose_name='pack_name'),
        ),
    ]
