# Generated by Django 4.0.3 on 2022-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_booking_package_pack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_package',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='pack_name'),
        ),
    ]
