# Generated by Django 4.0.3 on 2022-04-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_booking_package_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_package',
            name='hotel_name',
        ),
    ]
