# Generated by Django 4.0.3 on 2022-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_booking_package_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_package',
            name='pack_price',
            field=models.IntegerField(null=True, verbose_name='pack_price'),
        ),
    ]
