# Generated by Django 4.0.3 on 2022-04-24 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking_package_pack_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_hotel',
            name='adults',
            field=models.IntegerField(default=2, verbose_name='adults'),
        ),
        migrations.AddField(
            model_name='booking_hotel',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='dob'),
        ),
        migrations.AddField(
            model_name='booking_hotel',
            name='image_1',
            field=models.ImageField(default='Insert Image', null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='booking_hotel',
            name='room_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='room_name'),
        ),
        migrations.AddField(
            model_name='booking_hotel',
            name='room_price_type_1',
            field=models.IntegerField(null=True, verbose_name='room_price_type_1'),
        ),
        migrations.AddField(
            model_name='booking_hotel',
            name='room_price_type_2',
            field=models.IntegerField(null=True, verbose_name='room_price_type_2'),
        ),
        migrations.AddField(
            model_name='booking_hotel',
            name='zipcode',
            field=models.CharField(blank=True, max_length=30, verbose_name='zipcode'),
        ),
    ]
